FROM python:3.11-slim

RUN useradd -m -u 1000 user

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PORT=8501 \
    P5_API_BASE_URL=https://rayakevin-p5-employee-attrition-api.hf.space \
    HOME=/home/user \
    PATH=/home/user/.local/bin:$PATH

WORKDIR $HOME/app

COPY --chown=user requirements.streamlit.txt ./

RUN pip install --upgrade pip && \
    pip install -r requirements.streamlit.txt

COPY --chown=user ui ./ui
COPY --chown=user .streamlit ./.streamlit
COPY --chown=user README.md ./

EXPOSE 8501

USER user

CMD ["sh", "-c", "streamlit run ui/streamlit_app.py --server.address 0.0.0.0 --server.port ${PORT}"]
